### ISSUE TITLE
chat has disappeared and I need help

### ISSUE THREAD

**Issue by tfink1975** [learn-co-curriculum/phase-1-array-filter-method-lab#6]
### Canvas Link

https://learning.flatironschool.com/courses/5300/assignments/179784?module_item_id=397026

### Concern

I would like to access customer service for help with a lab but the chat option has disappeared.

**Comment by lizbur10** [comment]
Hi @tfink1975! Chat was closed for the Labor Day holiday - I'm guessing that's why you weren't seeing the chat box. Apologies for the inconvenience!

I'm going to go ahead and close this issue, but if you are still unable to access chat please reopen it 💙
